### ISSUE TITLE
Configure log rotation

### ISSUE THREAD

**Issue by adacey** [NitriKx/docker-Plex-Cleaner#6]
Currently, the plexcleaner.log continues to grow indefinitely. I just cleared mine where it had hit over 24gb of data. Where the cron job runs every 5 minutes by default and appends the log file it very quickly grows in size. It would be quite useful if that file were rotated on a daily basis and only a week's worth of logs kept by default.

**Comment by NitriKx** [comment]
Fixed in 2.03.1

**Comment by adacey** [comment]
Not fixed, logrotate fails to run. First, complaining about the permissions on plexcleaner.conf, then on the ownership of the logs dir:

```
bash-5.1# /etc/periodic/daily/logrotate 
Potentially dangerous mode on plexcleaner.conf: 0666
error: Ignoring plexcleaner.conf because it is writable by group or others.
error: stat of /var/log/messages failed: No such file or directory
bash-5.1# chmod 644 /etc/logrotate.d/plexcleaner.conf
bash-5.1# /etc/periodic/daily/logrotate
error: stat of /var/log/messages failed: No such file or directory
error: skipping "/logs/plexcleaner.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```

**Comment by NitriKx** [comment]
Thanks for the feedback, I'll try to fix it today

**Comment by NitriKx** [comment]
Should be fixed in 2.03.2
